network:
  version: 2
  ethernets:
    enp0s3:
      dhcp4: no
      addresses: [10.0.2.103/24]
      routes:
        - to: default
          via: 10.0.2.2
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]

    enp0s8:
      dhcp4: no
      addresses: [192.168.56.103/24]
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]