network:
  version: 2
  ethernets:
    enp0s3:
      dhcp4: no
      addresses: [10.0.2.101/24] #Change for replicas and other nodes 
      gateway4: 10.0.2.2
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]