global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:9187']

  - job_name: 'node-healthcheck'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9100']